# Generated by Django 4.1.5 on 2023-02-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_rename_tag_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scopes',
            new_name='tag',
        ),
    ]
